### ISSUE TITLE
Make sessionKeepAlive work with different theme

### ISSUE THREAD

**Issue by tehwalris** [PhaserArray/moodle-tweaks#7]
The logo of my university in Moodle does not match `a.navbar-brand`, so `sessionKeepAlive.js` crashes (`Cannot read property 'getAttribute' of null` on line 6). Could you use `window.location.origin` as `targetURL` instead? Or is there a special reason that the URL has to come from the logo?

**Comment by PhaserArray** [comment]
I can't recall a specific reason for using the href from that element over the the window origin. I will make the change in the next release.

**Comment by PhaserArray** [comment]
Fixed with commit 9606c0f0c9746cb75e64165a310a490515907fa4
